export {default as Home} from './Home'
export {default as Blogs} from './Blogs'
export {default as Contact} from './Contact'
export {default as About} from './About'
export {default as Properties} from './Properties'
export {default as News} from './News'